# File Tree: charmacy_chatbot_vanna

**Generated:** 3/26/2026, 9:26:53 PM
**Root Path:** `d:\AI__ML__Projects__Code\Avnish\charmacy_chatbot_vanna`

```
├── 📁 charts
│   ├── 📁 templates
│   │   ├── ⚙️ area.json
│   │   ├── ⚙️ bar_horizontal.json
│   │   ├── ⚙️ bar_vertical.json
│   │   ├── ⚙️ bubble.json
│   │   ├── ⚙️ diverging_bar.json
│   │   ├── ⚙️ donut.json
│   │   ├── ⚙️ grouped_bar.json
│   │   ├── ⚙️ heatmap.json
│   │   ├── ⚙️ histogram.json
│   │   ├── ⚙️ kpi_card.json
│   │   ├── ⚙️ line.json
│   │   ├── ⚙️ multi_line.json
│   │   ├── ⚙️ pie.json
│   │   ├── ⚙️ scatter.json
│   │   └── ⚙️ table.json
│   ├── 🐍 chart_spec_generator.py
│   ├── 🐍 chart_type_selector.py
│   ├── 🐍 data_shape_analyzer.py
│   ├── 🐍 edge_case_handler.py
│   ├── 🐍 insight_annotator.py
│   └── 🐍 theme_engine.py
├── 📁 config
│   ├── ⚙️ chart_theme.json
│   ├── ⚙️ database.yaml
│   ├── ⚙️ rules.yaml
│   └── ⚙️ vanna_config.yaml
├── 📁 core
│   ├── 🐍 error_recovery.py
│   ├── 🐍 sql_validator.py
│   └── 🐍 vanna_instance.py
├── 📁 feedback
│   ├── 🐍 __init__.py
│   ├── 🐍 analytics.py
│   ├── 🐍 example_manager.py
│   └── 🐍 feedback_collector.py
├── 📁 logs
├── 📁 persistence
│   ├── 🐍 __init__.py
│   ├── 📄 queries.db
│   └── 🐍 sqlite_store.py
├── 📁 scripts
│   ├── 🐍 introspect_ssms.py
│   ├── 🐍 test_connection.py
│   └── 🐍 train_vanna.py
├── 📁 streamlit_app
│   ├── 📁 components
│   │   ├── 🐍 __init__.py
│   │   ├── 🐍 chart_renderer.py
│   │   ├── 🐍 chat.py
│   │   ├── 🐍 data_table.py
│   │   ├── 🐍 feedback_bar.py
│   │   ├── 🐍 kpi_card.py
│   │   └── 🐍 sql_viewer.py
│   ├── 📁 pages
│   │   ├── 🐍 01_chat.py
│   │   ├── 🐍 02_history.py
│   │   ├── 🐍 03_admin.py
│   │   └── 🐍 __init__.py
│   └── 🐍 app.py
├── 📁 training
│   ├── 📁 ddl
│   │   ├── 📄 00_EAN_Master.sql
│   │   ├── 📄 01_Amazon_B2C_Daily.sql
│   │   ├── 📄 02_Flipkart_B2C_Daily.sql
│   │   ├── 📄 03_Myntra_B2C_Daily.sql
│   │   ├── 📄 04_Shopify_B2C_Daily.sql
│   │   ├── 📄 05_Nykaa_B2B_Secondary_Daily.sql
│   │   ├── 📄 06_Zepto_B2B_Secondary_Daily.sql
│   │   ├── 📄 07_Amazon_B2B_Daily.sql
│   │   └── 📄 08_B2B_B2C_VIEW.sql
│   ├── 📁 documentation
│   │   ├── 📝 business_rules.md
│   │   ├── 📝 column_definitions.md
│   │   ├── 📝 glossary.md
│   │   └── 📝 tsql_rules.md
│   └── 📁 examples
│       └── ⚙️ seed_examples.json
├── 📁 vectordb
│   ├── 📁 6133bc86-21ba-4d3e-a98a-0926b8930b35
│   │   ├── ⚙️ data_level0.bin
│   │   ├── ⚙️ header.bin
│   │   ├── ⚙️ length.bin
│   │   └── ⚙️ link_lists.bin
│   ├── 📁 b5c0d978-de80-4376-8109-52a801c17a9c
│   │   ├── ⚙️ data_level0.bin
│   │   ├── ⚙️ header.bin
│   │   ├── ⚙️ length.bin
│   │   └── ⚙️ link_lists.bin
│   ├── 📁 bac3dfe7-7d2e-4d13-ba44-9552d9fa6842
│   │   ├── ⚙️ data_level0.bin
│   │   ├── ⚙️ header.bin
│   │   ├── ⚙️ length.bin
│   │   └── ⚙️ link_lists.bin
│   └── 📄 chroma.sqlite3
├── 📄 Untitled-1.litcoffee
├── 📝 readme.md
└── 📄 requirements.txt
```

---
*Generated by FileTree Pro Extension*