"""
scripts/train_vanna.py

One-time training script for the Charmacy Milano text-to-SQL chatbot.

Three training phases:
    STEP 1 — DDL:           Load .sql files from training/ddl/
    STEP 2 — Documentation: Load .md files from training/documentation/
    STEP 3 — Q→SQL Examples: Load from training/examples/seed_examples.json

Usage:
    python scripts/train_vanna.py                    # Train all 3 phases
    python scripts/train_vanna.py --ddl-only         # DDL only
    python scripts/train_vanna.py --docs-only        # Documentation only
    python scripts/train_vanna.py --examples-only    # Examples only
    python scripts/train_vanna.py --reset            # Wipe all + retrain
    python scripts/train_vanna.py --dry-run          # Preview without training

After training, verify with:
    python scripts/test_connection.py
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(name)s] %(levelname)s: %(message)s",
)
logger = logging.getLogger(__name__)

# ── Paths ────────────────────────────────────────────────────────────────────
TRAINING_DIR = ROOT / "training"
DDL_DIR = TRAINING_DIR / "ddl"
DOCS_DIR = TRAINING_DIR / "documentation"
EXAMPLES_FILE = TRAINING_DIR / "examples" / "seed_examples.json"

# ── T-SQL rules (imported from vanna_instance for DRY) ───────────────────────
from core.vanna_instance import get_vanna, TSQL_RULES


def _print_header(title: str) -> None:
    print("\n" + "=" * 70)
    print(f"  {title}")
    print("=" * 70)


def _print_result(label: str, success: bool, detail: str = "") -> None:
    icon = "✅" if success else "❌"
    msg = f"  {icon} {label}"
    if detail:
        msg += f" — {detail}"
    print(msg)


# ── STEP 1: Train DDL ───────────────────────────────────────────────────────

def train_ddl(vn, dry_run: bool = False) -> int:
    """
    Load all .sql files from training/ddl/ and train each as DDL.

    Files should contain CREATE TABLE/VIEW statements with column
    definitions, constraints, sample data comments, and row counts
    (as generated by scripts/introspect_ssms.py).

    Returns:
        Number of DDL files successfully trained.
    """
    _print_header("STEP 1 — DDL Schema Training")

    if not DDL_DIR.exists():
        print(f"  ⚠️  DDL directory not found: {DDL_DIR}")
        print(f"      Create .sql files or run: python scripts/introspect_ssms.py --output training/ddl/")
        return 0

    sql_files = sorted(DDL_DIR.glob("*.sql"))
    if not sql_files:
        print(f"  ⚠️  No .sql files found in {DDL_DIR}")
        return 0

    print(f"  Found {len(sql_files)} DDL files:")
    trained = 0

    for sql_file in sql_files:
        filename = sql_file.name
        content = sql_file.read_text(encoding="utf-8").strip()

        if not content:
            _print_result(filename, False, "empty file — skipped")
            continue

        # Truncate display for logging
        preview = content[:120].replace("\n", " ") + "…"
        print(f"\n  📄 {filename} ({len(content):,} chars)")
        print(f"     Preview: {preview}")

        if dry_run:
            _print_result(filename, True, "DRY RUN — not trained")
            trained += 1
            continue

        try:
            vn.train(ddl=content)
            _print_result(filename, True, "trained")
            trained += 1
        except Exception as exc:
            _print_result(filename, False, str(exc)[:120])

    print(f"\n  DDL training complete: {trained}/{len(sql_files)} files")
    return trained


# ── STEP 2: Train Documentation ─────────────────────────────────────────────

def train_documentation(vn, dry_run: bool = False) -> int:
    """
    Load all .md files from training/documentation/ and train each
    as a documentation chunk.

    Also trains the T-SQL rules from core/vanna_instance.py (the same
    rules injected into every prompt) as a standalone doc chunk, so
    RAG retrieval can surface them independently of prompt injection.

    Returns:
        Number of documentation chunks successfully trained.
    """
    _print_header("STEP 2 — Documentation Training")

    trained = 0

    # ── 2a. Train T-SQL rules as documentation ───────────────────────────
    print("\n  📝 T-SQL Rules (from vanna_instance.py)")
    if dry_run:
        _print_result("T-SQL rules", True, "DRY RUN — not trained")
        trained += 1
    else:
        try:
            vn.train(documentation=TSQL_RULES)
            _print_result("T-SQL rules", True, f"{len(TSQL_RULES):,} chars")
            trained += 1
        except Exception as exc:
            _print_result("T-SQL rules", False, str(exc)[:120])

    # ── 2b. Train critical business rules inline ─────────────────────────
    critical_docs = [
        (
            "MRP definition",
            "MRP is the TOTAL line-item amount (quantity × unit price), NOT the unit price. "
            "SUM(MRP) = Total Revenue. Per-unit price = MRP / NULLIF(quantity, 0). "
            "SUM(MRP) / NULLIF(SUM(quantity), 0) = Average Selling Price (ASP). "
            "Never use AVG(MRP) for average price."
        ),
        (
            "Net sales filter",
            "Always apply the net sales filter to exclude cancelled/returned/unfulfilled rows: "
            "WHERE NOT ( "
            "(platform = 'Amazon' AND ISNULL(transaction_type,'') IN ('Cancel','Refund','FreeReplacement')) "
            "OR (platform = 'Flipkart' AND ISNULL(event_sub_type,'') IN ('Cancellation','Return','RTO')) "
            "OR (platform = 'Shopify' AND ISNULL(fulfilment_type,'') = 'unfulfilled') )"
        ),
        (
            "Order counting rules",
            "Order counting differs by platform: "
            "Amazon/Flipkart/Myntra → COUNT(DISTINCT order_id). "
            "Nykaa → SUM(total_orders). "
            "Shopify/Zepto → COUNT(*) because order_id is NULL. "
            "Cross-platform total = "
            "COUNT(DISTINCT CASE WHEN platform IN ('Amazon','Flipkart','Myntra') THEN order_id END) "
            "+ SUM(CASE WHEN platform = 'Nykaa' THEN total_orders ELSE 0 END) "
            "+ COUNT(CASE WHEN platform IN ('Shopify','Zepto') THEN 1 END)"
        ),
        (
            "Shopify has no order_date",
            "Shopify rows have NULL order_date for ALL rows. "
            "Any date filter (WHERE order_date >= ...) will silently exclude all Shopify data. "
            "Amazon also has ~87 rows with NULL order_date."
        ),
        (
            "State name normalization",
            "ship_to_state has mixed formats — abbreviation AND full name for 20 states. "
            "Always use IN() with both spellings: "
            "'Up','Uttar pradesh', 'Mh','Maharashtra', 'Dl','Delhi', 'Pb','Punjab', "
            "'Gj','Gujarat', 'Hr','Haryana', 'Wb','West bengal', 'Mp','Madhya pradesh', "
            "'Ka','Karnataka', 'Rj','Rajasthan', 'Br','Bihar', 'Ts','Tg','Telangana', "
            "'Jh','Jharkhand', 'Tn','Tamil nadu', 'Or','Odisha', 'As','Assam', "
            "'Uk','Ut','Uttarakhand', 'Kl','Kerala'"
        ),
        (
            "Product grouping rules",
            "product_name, article_type, sku_code, and EAN are NULL for ~34% of rows "
            "(products not in EAN_Master). "
            "Always add WHERE product_name IS NOT NULL when grouping by product. "
            "Use product_name for grouping — NEVER product_description (raw/unstandardised)."
        ),
        (
            "Primary vs Secondary salestype",
            "Never mix Primary and Secondary salestype in one revenue sum. "
            "Primary = Amazon, Flipkart, Myntra, Shopify, Amazon B2B (brand revenue). "
            "Secondary = Nykaa, Zepto (sell-through tracking only, not brand revenue)."
        ),
        (
            "Month year sorting",
            "month_year column values like 'Jan 2026' sort alphabetically, not chronologically. "
            "Always use ORDER BY MIN(order_date) instead of ORDER BY month_year."
        ),
    ]

    for label, doc_text in critical_docs:
        print(f"\n  📝 {label}")
        if dry_run:
            _print_result(label, True, "DRY RUN")
            trained += 1
        else:
            try:
                vn.train(documentation=doc_text)
                _print_result(label, True, f"{len(doc_text)} chars")
                trained += 1
            except Exception as exc:
                _print_result(label, False, str(exc)[:120])

    # ── 2c. Train .md files from documentation directory ─────────────────
    if DOCS_DIR.exists():
        md_files = sorted(DOCS_DIR.glob("*.md"))
        print(f"\n  Found {len(md_files)} documentation files:")

        for md_file in md_files:
            filename = md_file.name
            content = md_file.read_text(encoding="utf-8").strip()

            if not content:
                _print_result(filename, False, "empty — skipped")
                continue

            # Split large docs into chunks (ChromaDB has token limits)
            chunks = _split_doc_into_chunks(content, max_chars=3000)

            for i, chunk in enumerate(chunks):
                chunk_label = f"{filename}" if len(chunks) == 1 else f"{filename} (part {i+1}/{len(chunks)})"
                print(f"\n  📝 {chunk_label} ({len(chunk):,} chars)")

                if dry_run:
                    _print_result(chunk_label, True, "DRY RUN")
                    trained += 1
                else:
                    try:
                        vn.train(documentation=chunk)
                        _print_result(chunk_label, True, "trained")
                        trained += 1
                    except Exception as exc:
                        _print_result(chunk_label, False, str(exc)[:120])
    else:
        print(f"  ⚠️  Documentation directory not found: {DOCS_DIR}")

    print(f"\n  Documentation training complete: {trained} chunks")
    return trained


def _split_doc_into_chunks(text: str, max_chars: int = 3000) -> list[str]:
    """Split a long document into chunks at paragraph boundaries."""
    if len(text) <= max_chars:
        return [text]

    chunks = []
    paragraphs = text.split("\n\n")
    current_chunk = ""

    for para in paragraphs:
        if len(current_chunk) + len(para) + 2 > max_chars and current_chunk:
            chunks.append(current_chunk.strip())
            current_chunk = para
        else:
            current_chunk += "\n\n" + para if current_chunk else para

    if current_chunk.strip():
        chunks.append(current_chunk.strip())

    return chunks if chunks else [text]


# ── STEP 3: Train Q→SQL Examples ────────────────────────────────────────────

def train_examples(vn, dry_run: bool = False) -> int:
    """
    Load Q→SQL examples from training/examples/seed_examples.json
    and train each pair.

    Expected JSON format:
    [
        {"question": "What is total revenue?", "sql": "SELECT SUM(MRP)..."},
        ...
    ]

    Returns:
        Number of examples successfully trained.
    """
    _print_header("STEP 3 — Q→SQL Example Training")

    if not EXAMPLES_FILE.exists():
        print(f"  ⚠️  Examples file not found: {EXAMPLES_FILE}")
        print(f"      Create it with Q→SQL pairs for best accuracy.")

        # Create the directory and a starter file
        EXAMPLES_FILE.parent.mkdir(parents=True, exist_ok=True)
        starter = _get_starter_examples()

        with open(EXAMPLES_FILE, "w", encoding="utf-8") as fh:
            json.dump(starter, fh, indent=2, ensure_ascii=False)
        print(f"      ✅ Created starter file with {len(starter)} examples.")
        print(f"      Edit it and re-run this script.")

        # Train the starter examples
        examples = starter
    else:
        try:
            with open(EXAMPLES_FILE, "r", encoding="utf-8") as fh:
                examples = json.load(fh)
        except json.JSONDecodeError as exc:
            print(f"  ❌ Invalid JSON in {EXAMPLES_FILE}: {exc}")
            return 0

    if not isinstance(examples, list):
        print(f"  ❌ Expected a JSON array, got {type(examples).__name__}")
        return 0

    print(f"  Found {len(examples)} Q→SQL examples")
    trained = 0
    failed = 0

    for i, item in enumerate(examples, 1):
        question = item.get("question", "").strip()
        sql = item.get("sql", "").strip()

        if not question or not sql:
            _print_result(f"Example {i}", False, "missing question or sql")
            failed += 1
            continue

        q_preview = question[:70] + "…" if len(question) > 70 else question
        print(f"\n  [{i}/{len(examples)}] Q: {q_preview}")

        if dry_run:
            _print_result(f"Example {i}", True, "DRY RUN")
            trained += 1
            continue

        try:
            vn.train(question=question, sql=sql)
            _print_result(f"Example {i}", True, "trained")
            trained += 1
        except Exception as exc:
            _print_result(f"Example {i}", False, str(exc)[:120])
            failed += 1

    print(f"\n  Example training complete: {trained}/{len(examples)} "
          f"(failed: {failed})")

    if trained < 20:
        print(f"\n  ⚠️  WARNING: Only {trained} examples trained.")
        print(f"      For reliable SQL generation, aim for 50+ diverse examples.")

    return trained


def _get_starter_examples() -> list[dict]:
    """Return starter Q→SQL examples for the Charmacy Milano dataset."""
    return [
        {
            "question": "What is the total revenue?",
            "sql": "SELECT SUM(MRP) AS total_revenue FROM [dbo].[B2B_B2C] WHERE NOT ((platform = 'Amazon' AND ISNULL(transaction_type,'') IN ('Cancel','Refund','FreeReplacement')) OR (platform = 'Flipkart' AND ISNULL(event_sub_type,'') IN ('Cancellation','Return','RTO')) OR (platform = 'Shopify' AND ISNULL(fulfilment_type,'') = 'unfulfilled'))"
        },
        {
            "question": "What is the total revenue by platform?",
            "sql": "SELECT platform, SUM(MRP) AS revenue, SUM(quantity) AS units FROM [dbo].[B2B_B2C] WHERE NOT ((platform = 'Amazon' AND ISNULL(transaction_type,'') IN ('Cancel','Refund','FreeReplacement')) OR (platform = 'Flipkart' AND ISNULL(event_sub_type,'') IN ('Cancellation','Return','RTO')) OR (platform = 'Shopify' AND ISNULL(fulfilment_type,'') = 'unfulfilled')) GROUP BY platform ORDER BY revenue DESC"
        },
        {
            "question": "Show monthly revenue trend",
            "sql": "SELECT month_year, SUM(MRP) AS revenue, SUM(quantity) AS units FROM [dbo].[B2B_B2C] WHERE month_year IS NOT NULL AND NOT ((platform = 'Amazon' AND ISNULL(transaction_type,'') IN ('Cancel','Refund','FreeReplacement')) OR (platform = 'Flipkart' AND ISNULL(event_sub_type,'') IN ('Cancellation','Return','RTO')) OR (platform = 'Shopify' AND ISNULL(fulfilment_type,'') = 'unfulfilled')) GROUP BY month_year ORDER BY MIN(order_date)"
        },
        {
            "question": "Top 10 products by revenue",
            "sql": "SELECT TOP 10 product_name, article_type, SUM(quantity) AS units, SUM(MRP) AS revenue FROM [dbo].[B2B_B2C] WHERE product_name IS NOT NULL AND NOT ((platform = 'Amazon' AND ISNULL(transaction_type,'') IN ('Cancel','Refund','FreeReplacement')) OR (platform = 'Flipkart' AND ISNULL(event_sub_type,'') IN ('Cancellation','Return','RTO')) OR (platform = 'Shopify' AND ISNULL(fulfilment_type,'') = 'unfulfilled')) GROUP BY product_name, article_type ORDER BY revenue DESC"
        },
        {
            "question": "What is the total number of units sold?",
            "sql": "SELECT SUM(CASE WHEN platform = 'Amazon' AND ISNULL(transaction_type,'') IN ('Cancel','Refund','FreeReplacement') THEN 0 WHEN platform = 'Flipkart' AND ISNULL(event_sub_type,'') IN ('Cancellation','Return','RTO') THEN 0 WHEN platform = 'Shopify' AND ISNULL(fulfilment_type,'') = 'unfulfilled' THEN 0 ELSE quantity END) AS total_units FROM [dbo].[B2B_B2C]"
        },
        {
            "question": "What is the average selling price?",
            "sql": "SELECT SUM(MRP) / NULLIF(SUM(quantity), 0) AS asp FROM [dbo].[B2B_B2C] WHERE NOT ((platform = 'Amazon' AND ISNULL(transaction_type,'') IN ('Cancel','Refund','FreeReplacement')) OR (platform = 'Flipkart' AND ISNULL(event_sub_type,'') IN ('Cancellation','Return','RTO')) OR (platform = 'Shopify' AND ISNULL(fulfilment_type,'') = 'unfulfilled'))"
        },
        {
            "question": "Revenue by article type",
            "sql": "SELECT article_type, SUM(MRP) AS revenue, SUM(quantity) AS units FROM [dbo].[B2B_B2C] WHERE article_type IS NOT NULL AND NOT ((platform = 'Amazon' AND ISNULL(transaction_type,'') IN ('Cancel','Refund','FreeReplacement')) OR (platform = 'Flipkart' AND ISNULL(event_sub_type,'') IN ('Cancellation','Return','RTO')) OR (platform = 'Shopify' AND ISNULL(fulfilment_type,'') = 'unfulfilled')) GROUP BY article_type ORDER BY revenue DESC"
        },
        {
            "question": "What is the cancellation rate?",
            "sql": "SELECT CAST(SUM(CASE WHEN (platform='Amazon' AND transaction_type='Cancel') OR (platform='Flipkart' AND event_sub_type='Cancellation') THEN 1 ELSE 0 END) AS FLOAT) / NULLIF(COUNT(*), 0) * 100 AS cancel_rate FROM [dbo].[B2B_B2C]"
        },
        {
            "question": "Revenue by state",
            "sql": "SELECT ship_to_state, SUM(MRP) AS revenue FROM [dbo].[B2B_B2C] WHERE ship_to_state IS NOT NULL AND NOT ((platform = 'Amazon' AND ISNULL(transaction_type,'') IN ('Cancel','Refund','FreeReplacement')) OR (platform = 'Flipkart' AND ISNULL(event_sub_type,'') IN ('Cancellation','Return','RTO')) OR (platform = 'Shopify' AND ISNULL(fulfilment_type,'') = 'unfulfilled')) GROUP BY ship_to_state ORDER BY revenue DESC"
        },
        {
            "question": "Compare B2B vs B2C revenue",
            "sql": "SELECT ordertype, SUM(MRP) AS revenue, SUM(quantity) AS units FROM [dbo].[B2B_B2C] WHERE NOT ((platform = 'Amazon' AND ISNULL(transaction_type,'') IN ('Cancel','Refund','FreeReplacement')) OR (platform = 'Flipkart' AND ISNULL(event_sub_type,'') IN ('Cancellation','Return','RTO')) OR (platform = 'Shopify' AND ISNULL(fulfilment_type,'') = 'unfulfilled')) GROUP BY ordertype ORDER BY revenue DESC"
        },
        {
            "question": "Top 5 states by number of orders",
            "sql": "SELECT TOP 5 ship_to_state, COUNT(DISTINCT CASE WHEN platform IN ('Amazon','Flipkart','Myntra') THEN order_id END) + COUNT(CASE WHEN platform IN ('Shopify','Zepto') THEN 1 END) AS total_orders FROM [dbo].[B2B_B2C] WHERE ship_to_state IS NOT NULL AND NOT ((platform = 'Amazon' AND ISNULL(transaction_type,'') IN ('Cancel','Refund','FreeReplacement')) OR (platform = 'Flipkart' AND ISNULL(event_sub_type,'') IN ('Cancellation','Return','RTO')) OR (platform = 'Shopify' AND ISNULL(fulfilment_type,'') = 'unfulfilled')) GROUP BY ship_to_state ORDER BY total_orders DESC"
        },
        {
            "question": "Average order value for Amazon",
            "sql": "SELECT SUM(MRP) / NULLIF(COUNT(DISTINCT order_id), 0) AS aov FROM [dbo].[B2B_B2C] WHERE platform = 'Amazon' AND NOT (ISNULL(transaction_type,'') IN ('Cancel','Refund','FreeReplacement'))"
        },
        {
            "question": "Monthly revenue trend for Flipkart",
            "sql": "SELECT month_year, SUM(MRP) AS revenue FROM [dbo].[B2B_B2C] WHERE platform = 'Flipkart' AND month_year IS NOT NULL AND NOT (ISNULL(event_sub_type,'') IN ('Cancellation','Return','RTO')) GROUP BY month_year ORDER BY MIN(order_date)"
        },
        {
            "question": "Nykaa discount percentage",
            "sql": "SELECT (SUM(display_price) - SUM(selling_price)) / NULLIF(SUM(display_price), 0) * 100 AS discount_pct FROM [dbo].[B2B_B2C] WHERE platform = 'Nykaa'"
        },
        {
            "question": "Revenue by payment method",
            "sql": "SELECT payment_method, SUM(MRP) AS revenue FROM [dbo].[B2B_B2C] WHERE payment_method IS NOT NULL AND NOT ((platform = 'Amazon' AND ISNULL(transaction_type,'') IN ('Cancel','Refund','FreeReplacement')) OR (platform = 'Flipkart' AND ISNULL(event_sub_type,'') IN ('Cancellation','Return','RTO')) OR (platform = 'Shopify' AND ISNULL(fulfilment_type,'') = 'unfulfilled')) GROUP BY payment_method ORDER BY revenue DESC"
        },
        {
            "question": "How many products do we sell?",
            "sql": "SELECT COUNT(DISTINCT product_name) AS product_count FROM [dbo].[B2B_B2C] WHERE product_name IS NOT NULL"
        },
        {
            "question": "Primary vs Secondary revenue",
            "sql": "SELECT salestype, SUM(MRP) AS revenue FROM [dbo].[B2B_B2C] WHERE NOT ((platform = 'Amazon' AND ISNULL(transaction_type,'') IN ('Cancel','Refund','FreeReplacement')) OR (platform = 'Flipkart' AND ISNULL(event_sub_type,'') IN ('Cancellation','Return','RTO')) OR (platform = 'Shopify' AND ISNULL(fulfilment_type,'') = 'unfulfilled')) GROUP BY salestype ORDER BY revenue DESC"
        },
        {
            "question": "Top 10 products by units sold on Amazon",
            "sql": "SELECT TOP 10 product_name, SUM(quantity) AS units FROM [dbo].[B2B_B2C] WHERE platform = 'Amazon' AND product_name IS NOT NULL AND NOT (ISNULL(transaction_type,'') IN ('Cancel','Refund','FreeReplacement')) GROUP BY product_name ORDER BY units DESC"
        },
        {
            "question": "Revenue from Foundation products",
            "sql": "SELECT product_name, SUM(MRP) AS revenue, SUM(quantity) AS units FROM [dbo].[B2B_B2C] WHERE article_type = 'Foundation' AND NOT ((platform = 'Amazon' AND ISNULL(transaction_type,'') IN ('Cancel','Refund','FreeReplacement')) OR (platform = 'Flipkart' AND ISNULL(event_sub_type,'') IN ('Cancellation','Return','RTO')) OR (platform = 'Shopify' AND ISNULL(fulfilment_type,'') = 'unfulfilled')) GROUP BY product_name ORDER BY revenue DESC"
        },
        {
            "question": "How many orders from Maharashtra?",
            "sql": "SELECT COUNT(DISTINCT CASE WHEN platform IN ('Amazon','Flipkart','Myntra') THEN order_id END) + COUNT(CASE WHEN platform IN ('Shopify','Zepto') THEN 1 END) AS total_orders FROM [dbo].[B2B_B2C] WHERE ship_to_state IN ('Maharashtra','Mh') AND NOT ((platform = 'Amazon' AND ISNULL(transaction_type,'') IN ('Cancel','Refund','FreeReplacement')) OR (platform = 'Flipkart' AND ISNULL(event_sub_type,'') IN ('Cancellation','Return','RTO')) OR (platform = 'Shopify' AND ISNULL(fulfilment_type,'') = 'unfulfilled'))"
        },
    ]


# ── Reset (wipe all training data) ──────────────────────────────────────────

def reset_training_data(vn) -> None:
    """Remove ALL training data from ChromaDB."""
    _print_header("RESET — Wiping All Training Data")

    try:
        training_df = vn.get_training_data()
    except Exception as exc:
        print(f"  ❌ Could not fetch training data: {exc}")
        return

    if training_df is None or training_df.empty:
        print("  ℹ️  No training data to delete.")
        return

    total = len(training_df)
    print(f"  Deleting {total} entries…")

    deleted = 0
    for row in training_df.itertuples(index=False):
        try:
            vn.remove_training_data(id=row.id)
            deleted += 1
        except Exception:
            pass

    print(f"  ✅ Deleted {deleted}/{total} entries.")


# ── Main ─────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Train Vanna with DDL, documentation, and Q→SQL examples."
    )
    parser.add_argument("--ddl-only", action="store_true", help="Train DDL only")
    parser.add_argument("--docs-only", action="store_true", help="Train documentation only")
    parser.add_argument("--examples-only", action="store_true", help="Train Q→SQL examples only")
    parser.add_argument("--reset", action="store_true", help="Wipe all training data first")
    parser.add_argument("--dry-run", action="store_true", help="Preview without training")
    args = parser.parse_args()

    train_all = not (args.ddl_only or args.docs_only or args.examples_only)

    print("\n╔════════════════════════════════════════════════════════════╗")
    print("║   CHARMACY MILANO — VANNA TRAINING PIPELINE               ║")
    print("╚════════════════════════════════════════════════════════════╝")

    if args.dry_run:
        print("\n  🏃 DRY RUN MODE — no training will be performed\n")

    # ── Initialize Vanna ─────────────────────────────────────────────────
    if not args.dry_run:
        print("\n  Initialising Vanna…")
        try:
            vn = get_vanna()
            print("  ✅ Vanna ready.")
        except Exception as exc:
            print(f"  ❌ Failed to initialise Vanna: {exc}")
            print("     Run 'python scripts/test_connection.py' to diagnose.")
            sys.exit(1)
    else:
        vn = None

    # ── Reset if requested ───────────────────────────────────────────────
    if args.reset and not args.dry_run:
        reset_training_data(vn)

    # ── Training phases ──────────────────────────────────────────────────
    start_time = time.time()
    totals = {"ddl": 0, "docs": 0, "examples": 0}

    if train_all or args.ddl_only:
        totals["ddl"] = train_ddl(vn, dry_run=args.dry_run)

    if train_all or args.docs_only:
        totals["docs"] = train_documentation(vn, dry_run=args.dry_run)

    if train_all or args.examples_only:
        totals["examples"] = train_examples(vn, dry_run=args.dry_run)

    elapsed = time.time() - start_time

    # ── Summary ──────────────────────────────────────────────────────────
    _print_header("TRAINING COMPLETE")
    print(f"  DDL schemas:     {totals['ddl']}")
    print(f"  Documentation:   {totals['docs']} chunks")
    print(f"  Q→SQL examples:  {totals['examples']}")
    print(f"  Total time:      {elapsed:.1f}s")

    # Verify
    if not args.dry_run:
        print("\n  Verifying…")
        summary = vn.training_summary()
        print(f"  ChromaDB now has: {summary.get('total', '?')} total entries")
        print(f"    DDL: {summary.get('ddl', '?')}")
        print(f"    Docs: {summary.get('documentation', '?')}")
        print(f"    Q→SQL: {summary.get('sql', '?')}")

        if summary.get("sql", 0) < 20:
            print("\n  ⚠️  Less than 20 Q→SQL examples. Add more for better accuracy.")

    print("\n  Done! 🎉\n")


if __name__ == "__main__":
    main()